name: Sentry Dart Plugin
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Analyze, Format and Build
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]

    steps:
        - uses: dart-lang/setup-dart@v1
          with:
            sdk: ${{ matrix.sdk }}
        - uses: actions/checkout@v2
        - name: Analyze and Format 
          run: |
            dart pub get
            dart analyze --fatal-infos
            dart format --set-exit-if-changed ./

        - uses: dart-lang/setup-dart@v1
          with:
            sdk: ${{ matrix.sdk }}
        - uses: actions/checkout@v2
        - name: Build
          run: |
            dart pub get
            dart compile aot-snapshot bin/sentry_dart_plugin.dart
