name: "Sentry Dart Plugin"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: "Analyze, Format and Build"
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev]

    steps:
        - uses: dart-lang/setup-dart@v1
          with:
            sdk: ${{ matrix.sdk }}

        - uses: actions/checkout@v2

        - name: "Pub Get"
          run: |
            dart pub get

        - name: "Analyze and Format"
          run: |
            dart analyze --fatal-infos
            dart format --set-exit-if-changed ./

        - name: Build
          run: |
            dart compile aot-snapshot bin/sentry_dart_plugin.dart
